version: '3.4'

services:
  thegalaxy.rabbitmq:
    image: 'rabbitmq:3.8.3-management-alpine'
    container_name: TheGalaxy.RabbitMQ
    ports:
      - '25672:5672'
      - '35672:15672'
    networks:
      - thegalaxy
  galacticsenate.consoleapp:
    image: ${DOCKER_REGISTRY-}galacticsenateconsoleapp
    build:
      context: .
      dockerfile: Source/GalacticSenate.ConsoleApp/Dockerfile
    depends_on:
        - galacticsenate.db
        - thegalaxy.rabbitmq
    networks:
      - thegalaxy
  galacticsenate.db:
    image: "mcr.microsoft.com/mssql/server"
    hostname: galacticsenatedb
    container_name: GalacticSenate.DB
    ports:
        - "14331:1433"
    environment:
        SA_PASSWORD: "qweasd!@!"
        ACCEPT_EULA: "Y"
    volumes:
       - ./data/data:/var/opt/mssql/data
       - ./data/log:/var/opt/mssql/log
       - ./data/secrets:/var/opt/mssql/secrets
    networks:
      - thegalaxy
  jediorder.web:
    image: ${DOCKER_REGISTRY-}jediorderweb
    ports:
       - "64014:443"
       - "64015:80"
    build:
      context: .
      dockerfile: Source/JediOrder.Web/Dockerfile
    networks:
      - thegalaxy
  galacticsenate.webapi:
    image: ${DOCKER_REGISTRY-}galacticsenatewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    ports:
       - "64016:443"
       - "64017:80"
    build:
      context: .
      dockerfile: Source/GalacticSenate.WebApi/Dockerfile
    networks:
      - thegalaxy
    depends_on:
        - galacticsenate.db
        - thegalaxy.rabbitmq
        - jediorder.web
networks:
  thegalaxy: {}
