version: '3.4'

services:
  celestial.rabbitmq:
    image: 'rabbitmq:3.8.3-management-alpine'
    ports:
      - '25672:5672'
      - '35672:15672'
    networks:
      - celestials
  galacticsenate.consoleapp:
    image: ${DOCKER_REGISTRY-}galacticsenateconsoleapp
    build:
      context: .
      dockerfile: Source/GalacticSenate.ConsoleApp/Dockerfile
    depends_on:
        - galacticsenate.db
        - celestial.rabbitmq
    networks:
      - celestials
  galacticsenate.db:
    image: "mcr.microsoft.com/mssql/server"
    hostname: galacticsenatedb
    container_name: galacticsenatedb
    ports:
        - "14331:1433"
    environment:
        SA_PASSWORD: "qweasd!@!"
        ACCEPT_EULA: "Y"
    volumes:
       - ./data/data:/var/opt/mssql/data
       - ./data/log:/var/opt/mssql/log
       - ./data/secrets:/var/opt/mssql/secrets
    networks:
      - celestials
  jediorder.web:
    image: ${DOCKER_REGISTRY-}jediorderweb
    ports:
       - "64014:443"
       - "64015:80"
    build:
      context: .
      dockerfile: Source/JediOrder.Web/Dockerfile
  galacticsenate.webapi:
    image: ${DOCKER_REGISTRY-}galacticsenatewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    ports:
       - "50767:443"
       - "50768:80"
    build:
      context: .
      dockerfile: Source/GalacticSenate.WebApi/Dockerfile
    networks:
      - celestials
    depends_on:
        - galacticsenate.db
        - celestial.rabbitmq
networks:
  celestials: {}
